### Лабораторна Робота №1
Робота Кисаріна Микити, 8 варіант

In [1]:
import numpy as np
import math

In [2]:
# Завдання №1. Створіть одновимірний масив (вектор) зі спадаючою послідовністю чисел, де кожне наступне число менше попереднього на 2, починаючи з 30, та виведіть його значення.
array_1 = np.arange(30, 0, -2)
array_1

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [3]:
# Завдання №2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями факторіалів натуральних чисел, починаючи з 1, та виведіть його значення.
rows, cols = 3, 3
matrix = np.matrix([[math.factorial(i * cols + j + 1) for j in range(cols)] for i in range(rows)])
matrix

matrix([[     1,      2,      6],
        [    24,    120,    720],
        [  5040,  40320, 362880]])

In [4]:
# Завдання №3. Створіть масив розміром 4x4, заповніть його випадковими цілими числами від 1 до 10 та виведіть його значення.
matrix = np.random.randint(11, size = (4, 4))
matrix

array([[ 6,  9, 10,  0],
       [ 3,  4,  6,  7],
       [ 9, 10,  0,  7],
       [ 3,  2,  2, 10]])

In [5]:
# Завдання №4. Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму всіх діагональних елементів.
matrix = np.random.rand(6, 6)
print(matrix)
np.trace(matrix)

[[0.00606486 0.48196177 0.62350142 0.73063518 0.97900187 0.92839538]
 [0.75016605 0.57264015 0.92865201 0.02056245 0.82327034 0.00158541]
 [0.28240302 0.08458839 0.82260191 0.90320705 0.45688568 0.00526636]
 [0.61265567 0.35529953 0.44287645 0.22342557 0.24519779 0.19077617]
 [0.46670193 0.43247502 0.22219104 0.42822438 0.78903932 0.03583123]
 [0.98674129 0.42276072 0.16215127 0.70949449 0.86388708 0.26474879]]


2.678520605866688

In [6]:
# Завдання №5. Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
array_1 = np.random.uniform(low=-10, high=10, size=4)
array_2 = np.random.uniform(low=-10, high=10, size=4)
print("Додавання:", array_1 + array_2)
print("Віднімання:", array_1 - array_2)
print("Множення:", array_1 * array_2)

Додавання: [ 5.65892071 -7.48709315  5.49812301  4.6043679 ]
Віднімання: [-0.43096205 -0.24687186  8.02490797 -9.64367912]
Множення: [  7.95941383  13.99890451  -8.54244784 -17.95008583]


In [7]:
# Завдання №6. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 5 та знайдіть їх добуток.
matrix_1 = np.random.randint(1, 6, size=16).reshape(4, 4)
matrix_2 = np.random.randint(1, 6, size=16).reshape(4, 4)
np.matmul(matrix_1, matrix_2)

array([[13, 11, 18, 12],
       [31, 33, 36, 26],
       [21, 17, 26, 14],
       [17, 17, 23, 14]])

In [8]:
# Завдання №7. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.
matrix_1 = np.array(np.random.randint(1,5, size=(2,3)))
matrix_2 = np.array(np.random.randint(1,5, size=(3,3)))
result = np.dot(matrix_1, matrix_2)
print(result)

[[30 13  8]
 [40 19 11]]


In [9]:
# Завдання №8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.
matrix = np.array(np.random.randint(1,8, size=(3,3)))
np.linalg.inv(matrix)

array([[ 0.65909091, -0.84090909, -0.13636364],
       [-0.04545455, -0.04545455,  0.18181818],
       [-0.11363636,  0.38636364, -0.04545455]])

In [10]:
# Завдання №9. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та транспонуйте її.
matrix = np.random.uniform(low=-5, high=5, size=25).reshape(5, 5)
np.transpose(matrix)

array([[-3.34052672, -2.19655761, -2.27911269, -2.3316481 , -4.56561934],
       [ 1.44622898,  3.54561249, -4.63942892,  1.23050672, -1.35236193],
       [ 2.54082578, -0.46285652, -0.40122811, -4.78237765,  3.76013016],
       [-2.47449467, -2.69968317,  3.80157566,  1.43463146,  3.42554131],
       [ 0.03372339,  4.58329437,  2.92237739, -4.53706479,  2.83810865]])

In [11]:
# Завдання №10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1 і знайдіть добуток матриці на вектор.
matrix = np.array(np.random.randint(1,11, size=(3, 4)))
vector = np.array(np.random.rand(4, 1))
result = np.dot(matrix, vector)
print(result)

[[ 9.91595416]
 [13.16783805]
 [16.57343539]]


In [12]:
# Завдання №11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
matrix = np.array(np.random.rand(2, 3))
vector = np.array(np.random.rand(3, 1))
result = np.dot(matrix, vector)
print(result)

[[1.07603951]
 [0.77480206]]


In [13]:
# Завдання №12. Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення елементів другої матриці до першої (поелементне ділення).
matrix_1 = np.array(np.random.randint(1,11, size=(9, 9)))
matrix_2 = np.array(np.random.randint(1,11, size=(9, 9)))
np.divide(matrix_2, matrix_1)

array([[3.5       , 3.        , 1.        , 2.        , 1.66666667,
        0.875     , 4.        , 3.33333333, 0.375     ],
       [1.        , 0.6       , 0.28571429, 0.33333333, 1.4       ,
        0.5       , 0.28571429, 0.33333333, 0.8       ],
       [0.4       , 3.33333333, 1.125     , 0.8       , 0.8       ,
        0.5       , 1.        , 1.66666667, 1.75      ],
       [1.6       , 0.6       , 1.66666667, 1.11111111, 8.        ,
        0.88888889, 2.25      , 2.66666667, 1.4       ],
       [1.        , 3.        , 1.16666667, 1.16666667, 0.88888889,
        1.33333333, 0.57142857, 0.2       , 0.14285714],
       [4.        , 5.        , 1.25      , 0.16666667, 7.        ,
        0.5       , 0.22222222, 0.33333333, 0.5       ],
       [3.        , 0.75      , 0.2       , 5.        , 2.25      ,
        1.33333333, 0.55555556, 0.125     , 7.        ],
       [1.4       , 3.33333333, 0.9       , 0.3       , 0.5       ,
        2.25      , 0.5       , 3.5       , 0.22222222],


In [14]:
# Завдання №13. Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть їх добуток
matrix_1 = np.array(np.random.randint(1,6, size=(9, 9)))
matrix_2 = np.array(np.random.randint(1,6, size=(9, 9)))
result = np.dot(matrix_1, matrix_2)
print(result)

[[ 80  88  59  87  67  85  72  85 100]
 [ 78  81  54  75  55  76  62  84  82]
 [ 91  93  70  97  87 107  83 104 111]
 [ 69  73  50  72  58  80  64  72  82]
 [ 69  72  54  76  65  81  62  72  88]
 [ 74  73  50  65  63  69  54  66  80]
 [ 56  57  48  50  46  60  59  60  65]
 [ 54  55  45  56  51  68  64  61  67]
 [ 68  72  56  81  63  83  69  80  89]]


In [15]:
# Завдання №14. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від -5 до 5 та знайдіть середнє арифметичне значення елементів матриці.
matrix_1 = np.array(np.random.randint(-5,5, size=(3, 3)))
print(matrix_1.mean())

-1.1111111111111112


In [2]:
# Завдання №15. Створіть матрицю розміром 10x10, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем значення елементу у кожному рядку матриці.
matrix = np.random.uniform(low=-2, high=2, size=100).reshape(10, 10)
vector = np.min(np.abs(matrix), axis=1)
vector

array([0.45292043, 0.33362422, 0.35796271, 0.10041353, 0.18005849,
       0.30374897, 0.50540112, 0.35036363, 0.09835943, 0.39367852])

In [17]:
# Висновки:
# У даній лабораторній роботі проведено роботу з бібліотекою Numpy та розібрано на практиці її методи створення масивів, матриць та векторів, виконано завдання з різними маніпуляціями проведеними над ними.